version: '2'
services:
  jenkins:
    container_name: JGM_Jenkins
    build:
      context: ./Build/Jenkins
    networks:
      - default_networks
    labels:
      kompose.service.type: nodeport
    ports:
      - '8080:8080'
      - '8443:8443'
      - '50000:50000'
    volumes:
      - '/Docker/JGM_Jenkins/Volumes:/bitnami/jenkins'
      - '/Docker/JGM_Jenkins/Volumes/.m2:/home/jenkins/.m2'
    command:
      sh -c "cp /usr/share/zoneinfo/Asia/Shanghai  /etc/localtime"
networks:
  default_networks:
    driver: bridge
    ipam:
      driver: def
          - subnet: 192.168.220.0/24
            gateway: 192.168.220.1
