version: '2'
services:
  jenkins:
    container_name: jenkins
    image: bitnami/jenkins:latest
    labels:
      kompose.service.type: nodeport
    ports:
      - '8080:8080'
      - '8443:8443'
      - '50000:50000'
    volumes:
      - '/Docker/Jenkins/Volumes:/bitnami/jenkins'
