version: '2'
services:
  jenkins:
    build:
      context: ./Build
    labels:
      kompose.service.type: nodeport
    ports:
      - '80:8080'
      - '443:8443'
      - '50000:50000'
    volumes:
      - '/Docker/Jenkins/Volumes:/bitnami/jenkins'
