version: '2'
services:
  redmine:
    image: 'bitnami/redmine:latest'
    ports:
      - '80:3000'
    environment:
      - REDMINE_DB_POSTGRES=postgresql
    volumes:
      - '/Docker/Redmine/Volumes:/bitnami'
    depends_on:
      - postgresql
  postgresql:
    image: 'bitnami/postgresql:latest'
    volumes:
      - '/Docker/Redmine_Postgresql/Volumes:/bitnami'
