version: '2'
services:
  postgresql:
    image: bitnami/postgresql:latest
    volumes:
      - /Docker/Redmine_Postgresql/Volumes:/bitnami
  redmine:
    image: bitnami/redmine:latest
    ports:
      - '3000:3000'
    environment:
      - REDMINE_DB_POSTGRES=postgresql
    volumes:
      - /Docker/Redmine/Volumes:/bitnami
    depends_on:
      - postgresql
