version: '2'
services:
  artifactory:
    container_name: artifactory
    image: docker.bintray.io/jfrog/artifactory-oss:6.5.9
    ports:
     - 8081:8081
    volumes:
     - /Docker/Jfrog/Volumes:/var/opt/jfrog/artifactory


        