version: '2'
services:
  logstash:
    container_name: ELK_Logstash
    build:
      context: Build/Logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - /Docker/ELK_Logstash/Volumes/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - /Docker/ELK_Logstash/Volumes/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5000:5000"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - default_networks
    depends_on:
      - elasticsearch
  elasticsearch:
    container_name: ELK_Elasticsearch
    build:
      context: Build/Elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - /Docker/ELK_Elasticsearch/Volumes/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - default_networks
  kibana:
    container_name: ELK_Kibana
    build:
      context: Build/Kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - /Docker/ELK_Kibana/Volumes/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    networks:
      - default_networks
    depends_on:
      - elasticsearch
networks:
  default_networks:
    driver: bridge
    ipam:
      driver: default
      config:
          - subnet: 192.168.220.0/24
            gateway: 192.168.220.1

