version: '2'
services:
  PostgreSQL:
    image: postgres:latest
    container_name: PostgreSQL
    volumes:
      - /Docker/PostgreSQL/Volumes:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=python
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    networks:
      gitlab_networks:
        ipv4_address: 192.168.220.21