FROM bitnami/jenkins:latest

LABEL maintainer="Vic Ying <rainying153@gmail.com>"

WORKDIR /root

RUN mkdir /home/jenkins

RUN mkdir /home/jenkins/.m2

RUN chmod -R 777 /home/jeckins

CMD []

EXPOSE 80 443 50000

	