version: '2'
services:
  artifactory:
    container_name: artifactory
    image: docker.bintray.io/jfrog/artifactory-oss:latest
    networks:
      jfrog_networks:
        ipv4_address: 192.168.220.11
    ports:
      - 8081:8081
    volumes:
      - /Docker/Jfrog/Volumes:/var/opt/jfrog/artifactory
networks:
  jfrog_networks:
    driver: bridge
    ipam:
      driver: default
      config:
          - subnet: 192.168.220.0/24
            gateway: 192.168.220.1